"""Shared cross-layer contracts (error DTO, §13 codes)."""

from contracts.errors import (
    DOMAIN_NO_MAGIC_ASSIGNMENT_CODE,
    DOMAIN_NO_MAGIC_ASSIGNMENT_MESSAGE,
    ErrorDetail,
    ErrorResponse,
    INPUT_BLANK_COUNT_INVALID_CODE,
    INPUT_BLANK_COUNT_INVALID_MESSAGE,
    INPUT_DUPLICATE_NON_ZERO_CODE,
    INPUT_DUPLICATE_NON_ZERO_MESSAGE,
    INPUT_SIZE_INVALID_CODE,
    INPUT_SIZE_INVALID_MESSAGE,
    INPUT_VALUE_RANGE_INVALID_CODE,
    INPUT_VALUE_RANGE_INVALID_MESSAGE,
)

__all__ = [
    "DOMAIN_NO_MAGIC_ASSIGNMENT_CODE",
    "DOMAIN_NO_MAGIC_ASSIGNMENT_MESSAGE",
    "ErrorDetail",
    "ErrorResponse",
    "INPUT_BLANK_COUNT_INVALID_CODE",
    "INPUT_BLANK_COUNT_INVALID_MESSAGE",
    "INPUT_DUPLICATE_NON_ZERO_CODE",
    "INPUT_DUPLICATE_NON_ZERO_MESSAGE",
    "INPUT_SIZE_INVALID_CODE",
    "INPUT_SIZE_INVALID_MESSAGE",
    "INPUT_VALUE_RANGE_INVALID_CODE",
    "INPUT_VALUE_RANGE_INVALID_MESSAGE",
]
